services:
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    platform: linux/amd64
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgres
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    platform: linux/amd64