services:
  nginx:
    image: nginx:latest
    depends_on:
      - wirecloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wirecloud-static:/var/www/static:ro
    ports:
      - '80:80'
    restart: always

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=wirepass # Change this password!
    restart: always

  wirecloud:
    image: oxixes/wirecloud:terrassa-demo
    depends_on:
      - postgres
    volumes:
      - wirecloud-data:/opt/wirecloud_instance/data
      - wirecloud-static:/var/www/static
    environment:
      - DEBUG=False
      - LOGLEVEL=INFO
      # - DEFAULT_THEME=wirecloud.defaulttheme
      - DB_HOST=postgres
      - DB_PASSWORD=wirepass # Change this password!
      - FORWARDED_ALLOW_IPS=*
      - WIRECLOUD_HTTPS_VERIFY=false
      # Uncomment the following environment variables to enable Keycloak IDM Integration
      # - SOCIAL_AUTH_KEYCLOAK_OIDC_URL=http://keycloak.orb.local:8080
      # - SOCIAL_AUTH_KEYCLOAK_OIDC_REALM=wirecloud
      # - SOCIAL_AUTH_KEYCLOAK_OIDC_KEY=terrassa_demo
      # - SOCIAL_AUTH_KEYCLOAK_OIDC_SECRET=wUb7ypRr2I0ZCeyyS9hfGer29fkAM5f8
      # - SOCIAL_AUTH_KEYCLOAK_OIDC_VERIFY_SSL=False
    restart: always

volumes:
  postgres-data:
  wirecloud-data:
  wirecloud-static:
